# KeyError is thrown when a key is not found

d1 = {'1': 'aa', '2': 'bb', '3': 'cc'}
d1['4']

# KeyError: '4'